import type { ScanResult, Finding, Severity } from '../patterns/types.js'

const SEVERITY_ORDER: Severity[] = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW']

const severityBadgeStyle: Record<Severity, string> = {
  CRITICAL: 'background:#dc2626;color:#fff',
  HIGH: 'background:#d97706;color:#fff',
  MEDIUM: 'background:#2563eb;color:#fff',
  LOW: 'background:#6b7280;color:#fff',
}

function badge(severity: Severity): string {
  return `<span style="${severityBadgeStyle[severity]};padding:2px 8px;border-radius:4px;font-size:12px;font-weight:600">${severity}</span>`
}

function findingsTable(findings: Finding[]): string {
  if (findings.length === 0) return '<p style="color:#16a34a;font-weight:600">No findings detected.</p>'

  const rows = findings
    .sort((first, second) => SEVERITY_ORDER.indexOf(first.severity) - SEVERITY_ORDER.indexOf(second.severity))
    .map(
      (finding) => `
    <tr>
      <td style="padding:8px 12px">${badge(finding.severity)}</td>
      <td style="padding:8px 12px;font-weight:500">${escapeHtml(finding.pattern)}</td>
      <td style="padding:8px 12px;font-family:monospace;font-size:13px;color:#6b7280">${escapeHtml(finding.file)}:${finding.line}</td>
      <td style="padding:8px 12px;font-family:monospace;font-size:13px">${escapeHtml(finding.masked)}</td>
    </tr>`
    )
    .join('')

  return `
  <table style="width:100%;border-collapse:collapse;border:1px solid #e5e7eb;border-radius:8px;overflow:hidden">
    <thead style="background:#f9fafb">
      <tr>
        <th style="padding:10px 12px;text-align:left;font-size:13px;color:#374151">Severity</th>
        <th style="padding:10px 12px;text-align:left;font-size:13px;color:#374151">Pattern</th>
        <th style="padding:10px 12px;text-align:left;font-size:13px;color:#374151">Location</th>
        <th style="padding:10px 12px;text-align:left;font-size:13px;color:#374151">Value (masked)</th>
      </tr>
    </thead>
    <tbody>${rows}</tbody>
  </table>`
}

function escapeHtml(text: string): string {
  return text.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;')
}

export function generateHtml(result: ScanResult): string {
  const critical = result.findings.filter((f) => f.severity === 'CRITICAL').length
  const high = result.findings.filter((f) => f.severity === 'HIGH').length
  const medium = result.findings.filter((f) => f.severity === 'MEDIUM').length
  const low = result.findings.filter((f) => f.severity === 'LOW').length

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>secretscan report</title>
</head>
<body style="font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;margin:0;padding:32px;background:#f9fafb;color:#111827">
  <div style="max-width:960px;margin:0 auto">
    <h1 style="font-size:24px;font-weight:700;margin-bottom:4px">secretscan report</h1>
    <p style="color:#6b7280;margin-bottom:32px">Scanned ${result.scanned} files in ${result.duration}ms</p>

    <div style="display:flex;gap:16px;margin-bottom:32px">
      <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:16px 24px;flex:1">
        <div style="font-size:28px;font-weight:700;color:#dc2626">${critical}</div>
        <div style="font-size:13px;color:#6b7280;margin-top:4px">CRITICAL</div>
      </div>
      <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:16px 24px;flex:1">
        <div style="font-size:28px;font-weight:700;color:#d97706">${high}</div>
        <div style="font-size:13px;color:#6b7280;margin-top:4px">HIGH</div>
      </div>
      <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:16px 24px;flex:1">
        <div style="font-size:28px;font-weight:700;color:#2563eb">${medium}</div>
        <div style="font-size:13px;color:#6b7280;margin-top:4px">MEDIUM</div>
      </div>
      <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:16px 24px;flex:1">
        <div style="font-size:28px;font-weight:700;color:#6b7280">${low}</div>
        <div style="font-size:13px;color:#6b7280;margin-top:4px">LOW</div>
      </div>
    </div>

    <div style="background:#fff;border:1px solid #e5e7eb;border-radius:8px;padding:24px">
      <h2 style="font-size:16px;font-weight:600;margin-top:0;margin-bottom:16px">Findings</h2>
      ${findingsTable(result.findings)}
    </div>

    <p style="color:#9ca3af;font-size:12px;margin-top:24px;text-align:center">
      Generated by <a href="https://github.com/chintanshah35/secretscan" style="color:#6b7280">secretscan</a>
    </p>
  </div>
</body>
</html>`
}
