export { scan } from './scanner/index.js'
export { allPatterns, piiPatterns, credentialPatterns } from './patterns/index.js'
export { getRemediation } from './remediation.js'
export { verifyFindings, canVerify } from './verify.js'
export type { ScanResult, Finding, Severity, PatternMatch, ScanOptions, Verification, VerificationStatus } from './patterns/types.js'
export type { Remediation } from './remediation.js'
